src/objects/Checkin__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <inlineHelpText>チェックインした位置の住所を別途保存</inlineHelpText>
        <label>住所</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationName__c</fullName>
        <inlineHelpText>お店の名前などチェックインした位置の名前を保存する</inlineHelpText>
        <label>ロケーション名</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NickName__c</fullName>
        <inlineHelpText>チェックインしたユーザのニックネームを保存する</inlineHelpText>
        <label>ニックネーム</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>チェックイン</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>チェックイン番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MapCtrl.cls
/**
 * チェックイン詳細画面用コントローラ
 **/
public with sharing class MapCtrl {

	/** チェックイン情報 **/
	public Checkin__c checkin {set; get;}

	/**
	 * ページ表示時の初期化処理
	 **/
	public PageReference init() {
		//リクエストパラメータで渡されたIDのチェックイン情報を取得
		List<Checkin__c> checkins = [select NickName__c, LocationName__c, Address__c, Location__Latitude__s, Location__Longitude__s, CreatedDate from Checkin__c where Id = :System.currentPageReference().getParameters().get('id')];
		if (checkins.size() == 1) {
			checkin = checkins.get(0);
		}
		return null;
	}

}