src/objects/Checkin__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <inlineHelpText>チェックインした位置の住所を別途保存</inlineHelpText>
        <label>住所</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationName__c</fullName>
        <inlineHelpText>お店の名前などチェックインした位置の名前を保存する</inlineHelpText>
        <label>ロケーション名</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <inlineHelpText>地理位置情報のオプション：小数
小数点の位置：15</inlineHelpText>
        <label>ロケーション</label>
        <scale>15</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>NickName__c</fullName>
        <inlineHelpText>チェックインしたユーザのニックネームを保存する</inlineHelpText>
        <label>ニックネーム</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>チェックイン</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>チェックイン番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SearchCheckinsCtrl.cls
/**
 * チェックイン履歴画面用のコントローラ
 **/
public with sharing class SearchCheckinsCtrl {

	/** 検索時の距離 **/
	public String distance {set; get;}

	/** チェックイン履歴の有無 **/
	public Boolean hasCheckins {set; get{
		return (checkins != null && checkins.size() > 0);
	}}

	/** チェックイン履歴 **/
	public List<Checkin__c> checkins {set; get;}

	/**
	 * ページ表示時の初期化処理
	 **/
	public PageReference init() {

		//リクエストパラメータから検索距離、緯度、経度を取得
		distance = System.currentPageReference().getParameters().get('distance');
		String latitude = System.currentPageReference().getParameters().get('latitude');
		String longitude = System.currentPageReference().getParameters().get('longitude');

		try {
			//検索距離、緯度、経度を指定してSOQLの実行
			checkins = Database.query(
				'select Id, Address__c, LocationName__c, NickName__c, CreatedDate from Checkin__c ' +
				'where DISTANCE(Location__c, GEOLOCATION(' + String.escapeSingleQuotes(latitude) + ',' + String.escapeSingleQuotes(longitude) + '), \'km\') < ' + String.escapeSingleQuotes(distance) + ' ' +
				'order by CreatedDate desc'
			);
		}
		catch (Exception e) {
			System.debug(e);
		}

		return null;
	}

}