src/objects/TestProjectMst__c.object
<CustomObject>
    <customHelpPage>TestProjectPage</customHelpPage>
    <description>プロジェクトマスタ</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>プロジェクトの終了日付を入力します</description>
        <label>終了日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>プロジェクトの責任者を選択します。</description>
        <label>責任者</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ManagerRelation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>プロジェクトの開始日を入力します。</description>
        <label>開始日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>プロジェクトの進行状況を選択します。</description>
        <label>進捗状況</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>開始前</fullName>
                    <default>true</default>
                    <label>開始前</label>
                </value>
                <value>
                    <fullName>進行中</fullName>
                </value>
                <value>
                    <fullName>終了済</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TestProjectName__c</fullName>
        <description>プロジェクトの名前</description>
        <inlineHelpText>最大255文字です。</inlineHelpText>
        <label>テストプロジェクト名</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>テストプロジェクト</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>テストプロジェクトＩＤ</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestEditProjectController.cls
public with sharing class TestEditProjectController {

	//遷移元ID
	public String selectionId {get; private set;}

	//新規フラグ
	public Boolean renderedRegistFlg {get; private set;}

	//更新フラグ
	public Boolean renderedUpdateFlg {get; private set;}

	//public TestProjectMst__c testProjectRec {get; private set;}
	public TestProjectMst__c testProjectRec {get; set;}

	//コンストラクタ
	public TestEditProjectController() {
		This.renderedRegistFlg = false;
		This.renderedUpdateFlg = false;
		This.testProjectRec = new TestProjectMst__c();
		//IDが渡ってきている場合、取得し更新モードへ
		This.selectionId = null;
		This.selectionId = System.currentPageReference().getParameters().get('hiddenId');

		if (This.selectionId != null) {
			This.renderedUpdateFlg = true;
			This.testProjectRec = [
									SELECT
										Name
										,TestProjectName__c
										,Status__c
										,StartDate__c
										,EndDate__c
										,Manager__c
									FROM
										TestProjectMst__c
									WHERE
										Name = :selectionId
									];
		} else {
			This.renderedRegistFlg = true;
		}
	}

	//登録処理
	public Pagereference registProject() {
		//入力チェック

		try {
			insert This.testProjectRec;
		} catch (Exception e) {
			//例外処理
		}

		//メッセージ設定

		//検索画面へ遷移
		return Page.TestSearchProject;
	}

	//更新処理
	public Pagereference updateProject() {
		//入力チェック

		try {
			update This.testProjectRec;
		} catch (Exception e) {
			//例外処理
		}

		//メッセージ設定

		//検索画面へ遷移
		return Page.TestSearchProject;
	}

	//削除処理
	public Pagereference deleteProject() {
		try {
			delete This.testProjectRec;
		} catch (Exception e) {
			//例外処理
		}

		//メッセージ設定

		//検索画面へ遷移
		return Page.TestSearchProject;
	}

	//戻る処理
	public Pagereference back() {
		return Page.TestSearchProject;
	}

}