src/objects/TestProjectMst__c.object
<CustomObject>
    <customHelpPage>TestProjectPage</customHelpPage>
    <description>プロジェクトマスタ</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>プロジェクトの終了日付を入力します</description>
        <label>終了日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>プロジェクトの責任者を選択します。</description>
        <label>責任者</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ManagerRelation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>プロジェクトの開始日を入力します。</description>
        <label>開始日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>プロジェクトの進行状況を選択します。</description>
        <label>進捗状況</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>開始前</fullName>
                    <default>true</default>
                    <label>開始前</label>
                </value>
                <value>
                    <fullName>進行中</fullName>
                </value>
                <value>
                    <fullName>終了済</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TestProjectName__c</fullName>
        <description>プロジェクトの名前</description>
        <inlineHelpText>最大255文字です。</inlineHelpText>
        <label>テストプロジェクト名</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>テストプロジェクト</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>テストプロジェクトＩＤ</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestSearchProjectController.cls
public with sharing class TestSearchProjectController {

    //検索条件：プロジェクト名
    public String searchProjectName {get; set;}

    //一覧レコード格納リスト
    public List<TestProjectMst__c> listProject {get; private set;}

    //レコード選択ID格納
    public String selectionId {get; private set;}

    //一覧表示フラグ
    public Boolean gridRenderedFlg {get; private set;}

    //コンストラクタ
    public TestSearchProjectController() {
        //検索条件・リスト一覧のクリア
        This.listProject = null;
        This.gridRenderedFlg = false;

        //検索項目の作成(リストボックス等)
    }

    //検索処理
    public PageReference searchProject() {
        //画面上の検索条件パラメータの取得
        //String projectName = Apexpages.currentPage().getParameters().get("searchProjectName");

        //一覧の取得
        This.listProject = null;

        /**This.listProject = [
                            SELECT
                                Name
                                ,TestProjectName__c
                                ,StartDate__c
                                ,EndDate__c
                                ,Manager__c
                                ,Status__c
                            FROM
                                TestProjectMst__c
                            WHERE
                            	Name like \'%\' + This.searchProjectName + \'%\'
                            ];*/
        String sql = 'SELECT Name ,TestProjectName__c ,StartDate__c,EndDate__c,Manager__c,Status__c FROM TestProjectMst__c ';

        if (This.searchProjectName != '') {
        	sql = sql + 'WHERE Name like \'%' + This.searchProjectName + '%';
        }

        //queryResult = Database.query(qryString) ;
        try {
        	This.listProject = Database.query(sql);
        } catch (Exception e) {
        	//例外処理
        }


		//一覧が取得できている場合、グリッドを表示する。
		if (This.listProject != null) {
			This.gridRenderedFlg = true;
		}

        return Page.TestSearchProject;
    }

    //新規登録押下時
    public Pagereference regist() {
        return Page.TestEditProject;
    }

    //編集画面遷移時
    public Pagereference edit() {
        //IDを設定し、編集画面へ遷移
        //TestSearchProject.getParameters().put('selectionId', This.selectionId);
        return Page.TestEditProject;
    }


}