src/objects/ToDoTest__c.object
<CustomObject>
    <description>行動テスト用カスタムオブジェクト</description>
    <fields>
        <fullName>ToName__c</fullName>
        <description>相手先の氏名を入力します。</description>
        <label>相手先氏名</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TodoList__c</fullName>
        <description>今回の行動を選択します。</description>
        <label>行動リスト</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>新規顧客</fullName>
                </value>
                <value>
                    <fullName>既存顧客</fullName>
                </value>
                <value>
                    <fullName>打ち合わせ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>行動テスト</label>
    <nameField>
        <label>行動テスト名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestToDoListController.cls
public with sharing class TestToDoListController {

    public String param =null;
    
    public void setParam(String s) {
        This.param = s;
    }
    
    public String getParam() {
        return This.param;
    }
    
    public Boolean renderedVal { get; set; }
    
    public Boolean renderedVal2 { get; set; }

    public String selectOption { get; set; }


    public ToDoTest__c toDoRec {get; set;}

    public String toName {get; set;}

    public String testName {get; set;}

    private final ToDoTest__c toDo;

    public TestToDoListController() {
        This.toDoRec = new ToDoTest__c();
        //This.testName = '濱野';
        This.renderedVal = true;
        This.renderedVal2 = false;
    }

    //リストボックスの切替を制御
    public PageReference chgToDoList() {
        This.toDoRec.toName__c = This.getParam();
        System.debug('chgToDoListkitayo');
        
        if (toDoRec.TodoList__c == '新規顧客') {
            This.renderedVal = true;
            This.renderedVal2 = false;
        } else {
            This.renderedVal = false;
            This.renderedVal2 = true;
        }
        
        return null;
    }
    
    public String getTestName() {
        return This.testName;
    }
}